ekf_filter_node:
  ros__parameters:

    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    publish_tf: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # ===================== IMU ============================
    imu0: "imu/data_raw"
    imu0_differential: false
    imu0_queue_size: 5
    imu0_config:
      - 0.0   # ori X
      - 0.0   # ori Y
      - 0.0   # ori Z
      - 1.0   # ang vel X
      - 1.0   # ang vel Y
      - 1.0   # ang vel Z
      - 0.0   # lin acc X
      - 0.0   # lin acc Y
      - 0.0   # lin acc Z
      - 1.0   # yaw
      - 1.0   # roll
      - 1.0   # pitch
      - 0.0
      - 0.0
      - 0.0

    # ===================== ODOM ============================
    odom0: "odom_raw"
    odom0_differential: false
    odom0_queue_size: 5
    odom0_config:
      - 1.0   # x
      - 1.0   # y
      - 0.0   # z
      - 0.0   # roll
      - 0.0   # pitch
      - 1.0   # yaw
      - 1.0   # v_x
      - 0.0   # v_y
      - 0.0   # v_z
      - 0.0   # roll_rate
      - 0.0   # pitch_rate
      - 1.0   # yaw_rate
      - 0.0   # a_x
      - 0.0   # a_y
      - 0.0   # a_z

    # ===================== PROCESS NOISE ====================
    process_noise_covariance:
      - 0.05
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.05
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.01
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.01
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.02

    # ===================== INITIAL COVARIANCE ===============
    initial_estimate_covariance:
      - 1e-9
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1e-9
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1e-9
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1e-9
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1e-9
